name: Test 
on: 
  push: 
    branches:
      - "main"
      
  
jobs:
  build:
    runs-on: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, windows-2022]
    strategy:
      matrix:
        words: ["3.7", "3.8", "3.9", "3.10", "hege"]
    steps:
      - run: echo ${{ matrix.words }}
