name: Test 
on: 
  push: 
    branches:
      - "main"
      
  
jobs:
  run_job:
    name: job1
    runs-on: [ubuntu-20.04]
    strategy:
      matrix:
        words: ["3.7", "3.8", "3.9", "3.10", "hege"]
    steps:
      - run: echo ${{ matrix.words }}
      - run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
  test_job:
    runs-on: [ubuntu-20.04]  
    steps:
    - run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
    - name: sx2
      id: first_step
    - run: echo "echo hello world ${{ steps.first_step.outputs.SELECTED_COLOR }}"
  
